### ISSUE TITLE
I am interested in maintaining it

### ISSUE THREAD

**Issue by dgonzalez** [olalonde/better-require#10]
Hi, I'll be interested in maintaining the repository.

Thanks

**Comment by olalonde** [comment]
Great, what is your username on npm?

**Comment by dgonzalez** [comment]
@dagonza is my username.

**Comment by dgonzalez** [comment]
Hello @olalonde, any progress on this? Thanks

**Comment by olalonde** [comment]
Added you as a collaborator on GH!

**Comment by dgonzalez** [comment]
Thanks!

2016-08-08 21:51 GMT+01:00 Oli Lalonde notifications@github.com:
